version: '3'

services: 
  db: 
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
